### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by SupchickCode** [Laraway/laraway.github.io#1]
Добавьте еще пункт что роуты нужно обернуть в мидлваер `\Fruitcake\Cors\HandleCors::class` ибо это не явный момент при переходе с старых версий или просто можно забыть

**Comment by Laraway** [comment]
Спасибо за комментарий, @SupchickCode.

В подразделе ["Старые версии"](https://laraway.github.io/cors/#old-version)  есть информация, о том, что необходимо использовать пакет [fruitcake/laravel-cors](https://github.com/fruitcake/laravel-cors) для 8.x или ниже, с ссылкой на него. 

Для [7.x](https://github.com/laravel/laravel/blob/3923e7f7c40368a5e78c1a33610191be8ad91e3b/app/Http/Kernel.php#L19) и [8.x](https://github.com/laravel/laravel/blob/78ad150a947f6677d9cb4e3eb9a257d312fe14c3/app/Http/Kernel.php#L19) пакет уже установлен и middleware `\Fruitcake\Cors\HandleCors` подключен в `App\Http\Kernel`, по умолчанию.

При глобальном использовании, дополнительно "оборачивать" маршруты не нужно. В `config/cors.php` указываются paths к которым будет применен middleware. Именно поэтому никакой дополнительной информации, по данному вопросу, в статье нет.

При самостоятельной установке пакета (любого) необходимо ознакомиться с документацией в README: [https://github.com/fruitcake/laravel-cors](https://github.com/fruitcake/laravel-cors) и следовать инструкции по установке, где есть раздел [Global usage](https://github.com/fruitcake/laravel-cors?tab=readme-ov-file#global-usage) с информацией о подключении middleware.

Тем не менее, согласен, что не подключенный middleware приведет к проблеме с CORS, поэтому обновил материал и добавил упоминание: [https://laraway.github.io/cors/#middleware](https://laraway.github.io/cors/#middleware). Спасибо за замечание.
